log:
  level: debug
  env: debug

remote_write:
  enabled: true
  url: http://prometheus:9090/api/v1/write
  interval: 5s

nats:
  url: nats://nats:4222

profiles:
  - name: job-1
    subject: test.1
    load: rare
    rate: 600
    duration: 10m

  - name: job-2
    subject: test.2
    load: periodic
    rate: 600
    duration: 10m

  - name: job-3
    subject: test.3
    load: random
    rate: 600
    duration: 10m

  - name: job-4
    subject: test.4
    load: constant
    rate: 600
    duration: 10m
